# Generated by Django 6.0.2 on 2026-03-20 12:01

import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, validators=[schedule.models.validate_start_date]),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[schedule.models.validate_age]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[schedule.models.validate_age]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True, validators=[schedule.models.validate_experience_years]),
        ),
    ]
